### ISSUE TITLE
Appcues URL scheme on Expo

### ISSUE THREAD

**Issue by georgibakken** [appcues/appcues-react-native-module#110]
Hi!

I am trying to setup Appcues Deep link/url scheme for Expo, following the [guide](https://github.com/appcues/appcues-react-native-module/blob/main/docs/ExpoManagedWorkflowURLSchemeConfiguring.md#configuring-the-appcues-url-scheme-with-the-expo-managed-workflow). However it gives me the error 1

> Error 1: indicates that the URL scheme is not registered as expected for appcues-APPCUES_APPLICATION_ID. 

![image](https://github.com/appcues/appcues-react-native-module/assets/16558100/cdc218d9-4c9c-4b35-8d11-e008a5caef12)

I can console log the scheme value that gives `appcues-******-****-****-****-*****b484`.

I have verified that the APPCUES_APPLICATION_ID matches.

Any tips on what's going wrong? 

It's a managed workflow in Expo SDK 49.

**Comment by iujames** [comment]
Hi @georgibakken , thank you for all the details here. Can you confirm the behavior you are seeing when you attempt to execute a deep link in your app, like `appcues-{app_id}://sdk/debugger`? Does it (A) not launch the app at all or (B) launch the app but not launch the debugger, or (C) something else?

When you mentioned that you console log the value, is that in the `Linking.useURL` hook? Possibly something in our debugger is not recognizing it quite correctly.

Also for reference, if you had not already seen - our troubleshooting doc on configuring deep links: https://docs.appcues.com/en_US/mobile-troubleshooting/troubleshoot-mobile-deep-links

Thank you!

**Comment by georgibakken** [comment]
Hi @iujames, thanks for the quick reply!

I am running a development build on my iPhone , running the development server with `npx expo start --dev-client`

[Testing the url](https://docs.expo.dev/guides/linking/#testing-urls), based on [this](https://stackoverflow.com/questions/71582823/how-to-open-deep-link-in-expo-dev-client), I have tried running

```npx uri-scheme open appcues-*******b484://192.168.86.23:8081/sdk/debugger --ios``` which gives
```
› iOS: Opening URI "appcues-*******b484://192.168.86.23:8081/sdk/debugger" in simulator
An error was encountered processing the command (domain=NSOSStatusErrorDomain, code=-10814):
Simulator device returned an error for the requested operation.
Underlying error (domain=NSOSStatusErrorDomain, code=-10814):
	The operation couldn’t be completed. (OSStatus error -10814.)

Aborting run
An unexpected error was encountered. Please report it as a bug:
Error: xcrun exited with non-zero code: 194
    at ChildProcess.completionListener (/Users/georg/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:28:163345)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (/Users/georg/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:28:162796)
    at Object.openAsync (/Users/georg/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:28:187061)
    at Object.openAsync (/Users/georg/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:28:191824)
    at Command.<anonymous> (/Users/georg/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:28:182828)
    at Command.listener (/Users/georg/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:28:166108)
    at Command.emit (node:events:513:28)
    at Command.parseArgs (/Users/georg/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:28:169306)
    at Command.parse (/Users/georg/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/build/index.js:28:167251)
    at Object.<anonymous> (/Users/georg/.npm/_npx/0475317ec596de5d/node_modules/uri-scheme/cli.js:5:9)
    at Module._compile (node:internal/modules/cjs/loader:1254:14) {
  pid: 31095,
  output: [ '', '' ],
  stdout: '',
  stderr: '',
  status: 194,
  signal: null
}
```

Opening `appcues-{app_id}://sdk/debugger` in safari for instance, doesn't work (not sure if it's supposed to)
I will try to make a non development build and see how that goes. 


The value I was console.logging was just the `scheme`. The `Linking.useURL` returns `null` in the development build. And thanks for the link, have already read it and as I understand I am experiencing Error 1. 

Based on the [guide](https://github.com/appcues/appcues-react-native-module/blob/main/docs/ExpoManagedWorkflowURLSchemeConfiguring.md) it seems like its
1. Setting the scheme
2. Handling the custom url
3. Make a development build
4. Verify in the debugger 
> To verify the URL scheme is registered and properly handled, open the Appcues debugger in your app with AppcuesWrapper.debug(), and tap the Appcues Deep Link row to check the configuration. If you see a green check mark, everything is set up properly!

I have followed these steps, but it doesn't give me the green check and it's a bit unclear for me how I can debug it. The troubleshooting doc just says to check if I use the correct application id.

**Comment by georgibakken** [comment]
Thank you so much for the descriptive and great help here! I figured out what it was, thanks for the Info.plist inspection in Xcode. 

I was setting the scheme via an `app.config.ts` where I read the env variable for the id. I have of course forgotten to add that env variable to expo.dev, so it was `undefined` when being built.

**Comment by iujames** [comment]
Great, glad to hear this is working now for you! Feel free to reach out here anytime should you need any other assistance with your Appcues usage.
