### ISSUE TITLE
Intermittent EXC_BAD_ACCESS Crash on iOS

### ISSUE THREAD

**Issue by ashfurrow** [appcues/appcues-react-native-module#128]
Hello 👋 I recently launched a React Native app using the `appcues-react-native` SDK and noticed some intermittent crashes coming from iOS. I can't reproduce the crash, but our crash reporter helped me track it down.

The crash happens on iOS 16.3.1, 17.1.1, and 17.1.2 on a variety of iPhone devices, from iPhone 12 to iPhone 15 Pro.

After the launch, I tried upgrading the `appcues-react-native` from `3.1.5` to `3.1.6`, but the crash persisted. The relevant part of our `Podfile.lock` is the following:

```
  - Appcues (3.1.4)
  - appcues-react-native (3.1.6):
    - Appcues (~> 3.1.4)
    - React-Core
```

Here is a symbolicated stack trace (where `Redacted` is the name of my app):

```
EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x8000000000000008.

0  libswiftCore.dylib +0x400034    _swift_isUniquelyReferenced_nonNull_native
1  Redacted +0xc77b0               specialized Dictionary._Variant.isUniquelyReferenced() (<compiler-generated>)
2  Redacted +0x25298               specialized Dictionary.subscript.setter (<compiler-generated>)
3  Redacted +0x24580               specialized DIContainer.resolve<A>(_:) (<compiler-generated>)
4  Redacted +0x25814               specialized DIContainer.resolve<A>(_:)
5  Redacted +0x158e7c              specialized DIContainer.resolve<A>(_:) (<compiler-generated>)
6  Redacted +0x24430               specialized thunk for @escaping @callee_guaranteed (@guaranteed DIContainer) -> (@out Any)
7  Redacted +0x25814               specialized DIContainer.resolve<A>(_:)
8  Redacted +0x1db5c               specialized DIContainer.resolve<A>(_:) (<compiler-generated>)
9  Redacted +0x135a8               closure #1 in ActivityProcessor.handleQualify(activity:completion:) (ActivityProcessor.swift:167:13)
10 Redacted +0x19d8fc              specialized closure #1 in NetworkClient.handleRequest<A>(_:requestId:completion:) (NetworkClient.swift:156:17)
11 Redacted +0x1a2398              partial apply for specialized closure #1 in NetworkClient.handleRequest<A>(_:requestId:completion:)
12 Redacted +0x19eee8              thunk for @escaping @callee_guaranteed @Sendable (@guaranteed Data?, @guaranteed NSURLResponse?, @guaranteed Error?) -> () (<compiler-generated>)
13 CFNetwork +0xf7b0               0x188de27b0 (0x188de25d0 + 480)
14 CFNetwork +0x2d6cc              0x188e006cc (0x188e00630 + 156)
15 libdispatch.dylib +0x26a4       __dispatch_call_block_and_release
16 libdispatch.dylib +0x42fc       __dispatch_client_callout
17 libdispatch.dylib +0xb890       __dispatch_lane_serial_drain
18 libdispatch.dylib +0xc3f4       __dispatch_lane_invoke
19 libdispatch.dylib +0x17000      __dispatch_root_queue_drain_deferred_wlh
20 libdispatch.dylib +0x16874      __dispatch_workloop_worker_thread
21 libsystem_pthread.dylib +0x1960 __pthread_wqthread
```

According to our crash breadcrumbs, each crash happens shortly after calling `Appcues.identify(userId, {mobile_app_language: userLocale})` (either after login or refreshing authentication credentials), and then calling `Appcues.screen(currentRouteName)`. Sometimes, two calls to `Appcues.screen(currentRouteName)` happen before the crash (depending on how we navigate the user). However, the crash always happens immediately after calling `.screen()` with the same `currentRouteName`. 

Do you have any suggestions? Is there any more detail I can provide to help track this down? Thank you!

**Comment by mmaatttt** [comment]
Hi @ashfurrow, thanks for stack trace and details, they're really helpful. It looks like some unlucky folks are hitting some multi-threading issues in our dependency injection implementation.

There's some updates I can to make it fully thread safe, but we'll want to test it carefully to ensure there's no unintended side effects. That probably means we're looking at Monday or Tuesday for a patch release.

**Comment by ashfurrow** [comment]
Hi @mmaatttt – thanks for the quick response. I’m glad I’m not the only one seeing this, at least! 

That solution and timeline sounds good to me. If the patch is ready by end-of-day Wednesday EST, I’m comfortable submitting an app update to Apple with the patch to verify it fixes the issue. Otherwise, I would wait for the new year 👍

**Comment by ashfurrow** [comment]
Not sure if this is the related to the iOS race condition, but I've seen a few of these crashes from Android as well:

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
        at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
        at com.appcuesreactnative.AppcuesWrapperView.addFragment$lambda$0(AppcuesFrameViewManager.kt:69)
        at com.appcuesreactnative.AppcuesWrapperView.$r8$lambda$PwGQtM6p_YMirBUuiVCLQmLKHgQ(Unknown)
        at com.appcuesreactnative.AppcuesWrapperView$$ExternalSyntheticLambda0.run(Unknown:4)
        at android.os.Handler.handleCallback(Handler.java:958)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:230)
        at android.os.Looper.loop(Looper.java:319)
        at android.app.ActivityThread.main(ActivityThread.java:8893)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

Seems to happen after the user backgrounds the app. This stacktrace was from `3.1.5`.

**Comment by mmaatttt** [comment]
@ashfurrow version 3.1.7 is available for you now. Fixes both the iOS and Android crashes.

**Comment by ashfurrow** [comment]
Awesome, thank you! I'll get on that deploy 👍

**Comment by ashfurrow** [comment]
Hello! This was released to iOS users Tuesday night (I'm blocked on Google Play Store deploys at the moment). I haven't seen any crashes on the new version. Users are still upgrading, and I'll reopen the issue if something goes wrong.

I have to say, I'm quite impressed with how quickly you addressed this issue. There are lots of SDKs out there that get distributed as precompiled binaries so it was refreshing to be able to examine the PRs that fixed this, read the new unit tests, learn about how you work. Great job 👍

**Comment by mmaatttt** [comment]
Cheers Ash, thanks for the kind words! We strongly believe in building our SDKs for the way we'd want to use them ourselves, and we love working with teams and developers like yourself who dig into the details to make the best possible products.
