### ISSUE TITLE
Implementation for Expo Router V3

### ISSUE THREAD

**Issue by jp1987** [appcues/appcues-react-native-module#147]
My project uses Expo Router V3, I followed [this documentation](https://github.com/appcues/appcues-react-native-module/blob/main/docs/ExpoManagedWorkflowURLSchemeConfiguring.md) to set up the scheme and `Linking` configuration. My debugger shows all green checks, including deep links.

Running `npx uri-scheme open "appcues-<appId>://sdk/debugger" --ios` opens the app, but Expo Router tries to navigate to `/sdk/debugger` because of the automatic linking configuration, and it throws a 404. I think [this issue](https://github.com/expo/expo/issues/27163) (although it's closed) is relevant.

How do I make the SDK work with Expo Router V3?

**Comment by mmaatttt** [comment]
Hi @jp1987,

This is a tricky one. Up until now, our own [Expo app](https://github.com/appcues/mobile-pattern-showcase-app) has had the same issue.

Expo Router is quite limited in its configuration options (the inevitable downfall of the "it just works automatically out of the box" promise), and that means that there's no way to stop it from treating every deep link as a route to navigate to. Exposing the linking config like the issue you linked proposed would be one solution, but sadly it doesn't sound like that's something that the Expo team will be implementing.

It is possible to fix the issue with a one-line patch to `node_modules/expo-router/build/getLinkingConfig.js`. Obviously that's not a great solution, but for reference, this patch would do the trick:

```
diff --git a/node_modules/expo-router/build/getLinkingConfig.js b/node_modules/expo-router/build/getLinkingConfig.js
index b6d4703..9f0f7c4 100644
--- a/node_modules/expo-router/build/getLinkingConfig.js
+++ b/node_modules/expo-router/build/getLinkingConfig.js
@@ -11,6 +11,8 @@ exports.getNavigationConfig = getNavigationConfig;
 function getLinkingConfig(routes) {
     return {
         prefixes: [],
+        // Filter out Appcues SDK deep links for router navigation
+        filter: (url) => !url.startsWith('appcues-'),
         // @ts-expect-error
         config: getNavigationConfig(routes),
         // A custom getInitialURL is used on native to ensure the app always starts at
```

I've just implemented this strategy in our app ([PR](https://github.com/appcues/mobile-pattern-showcase-app/pull/51)) and [this thread](https://github.com/expo/router/discussions/245) does something similar for a slightly different issue.

It's also ok to work around the issue by navigating back from the 404 screen each time an appcues deep link is opened. It's certainly annoying, but generally won't cause issues using the Appcues SDK.

**Comment by jp1987** [comment]
Appreciate your response @mmaatttt, I will try the fix.

Good news, it looks like Expo will allow access to the linking prop, see https://github.com/expo/expo/pull/27757

**Comment by mmaatttt** [comment]
That is good news, thanks for sharing the link!

As it currently stands, I don't think that PR will fully enable a fix for Appcues because,

1. it doesn't allow a `linking.filter` value, and
2. the implementation for `linking.prefixes` (which is now overridable in that PR) isn't fully fleshed out yet. In isolation, this change should do the trick, but as I discovered in my testing, I needed to use `filter` instead of `prefixes` because the expo fork of some react-navigation code seems to assume there are no prefixes:

Compare react navigation:

https://github.com/react-navigation/react-navigation/blob/a41d932198d1b48d84f410be1633fc5ddcb2df3f/packages/native/src/useLinking.native.tsx#L123-L136

vs the expo fork:

https://github.com/expo/expo/blob/4b34b0c955903403529d13d2dc8ddae5c5f7e098/packages/expo-router/src/fork/useLinking.native.ts#L125-L134

The react navigation implementation passes the prefixes ref to `extractPathFromURL` whereas `extractExpoPathFromURL` doesn't include the prefixes.

**Comment by mmaatttt** [comment]
Hi @jp1987, here's a new `expo-router+3.5.12.patch`:

```
diff --git a/node_modules/expo-router/build/getLinkingConfig.js b/node_modules/expo-router/build/getLinkingConfig.js
index 36633f0..171ccdf 100644
--- a/node_modules/expo-router/build/getLinkingConfig.js
+++ b/node_modules/expo-router/build/getLinkingConfig.js
@@ -21,6 +21,8 @@ function getLinkingConfig(routes, context, { metaOnly = true, serverUrl } = {})
         : undefined;
     return {
         prefixes: [],
+        // Filter out Appcues SDK deep links for router navigation
+        filter: (url) => !url.startsWith('appcues-'),
         config: getNavigationConfig(routes, metaOnly),
         // A custom getInitialURL is used on native to ensure the app always starts at
         // the root path if it's launched from something other than a deep link.
```

Also, it appears there's some new functionality in SDK 51 that might make this patch unnecessary, but I haven't had a chance to look into it.
- PR: https://github.com/expo/expo/pull/28113
- Example: https://github.com/expo/expo/pull/28689#issuecomment-2101711825

**Comment by jp1987** [comment]
@mmaatttt thanks for the super quick response, I didn't realise it was pretty much the same patch, just saw my patch fail and didn't look any further. Sorry, could've solved this myself. But thanks! :)

**Comment by mmaatttt** [comment]
No worries, I would've needed to look into it myself either way.

I've just finished testing out the new `+native-intent` functionality, and it does in fact replace the need for the patch, so I'd recommend trying this out first.

Create `./app/+native-intent.ts` with the following contents:

```ts
export function redirectSystemPath(event: {
  path: string | null;
  initial: boolean;
}) {
  // Filter out Appcues SDK deep links for router navigation
  if (event.path?.startsWith('appcues-')) {
    return null;
  }
  return event.path;
}
```
