### ISSUE TITLE
debug seems to block interactions on iPad simulator

### ISSUE THREAD

**Issue by kevinbror** [appcues/appcues-react-native-module#148]
Versions:

- react-native 0.72.10
- @appcues/react-native 3.1.12
- iOS 17.4 (iPad Air 5th gen)
- xcode 15.3

Issue: 

When running app on an iPad simulator with Appcues debug on all screen interactions are blocked. I can't press or swipe. It works fine on the iPhone simulator. I don't see any errors in the debug logs or my console.

**Comment by mmaatttt** [comment]
Hi @kevinbror, thanks for the bug report. We've just released version 3.1.13 that fixes the issue.

**Comment by kevinbror** [comment]
@mmaatttt awesome, thanks for the speedy turn around. I updated and it's looking good on iPad.
