### ISSUE TITLE
Unable to show experience {experienceId}

### ISSUE THREAD

**Issue by jp1987** [appcues/appcues-react-native-module#152]
My team has made a flow with an anchored tooltip that we manually trigger:

```
onPress={() => {
   Appcues.show(id);
}}
```

We sporadically get the "unable to show experience {id}" error. There's no real pattern to this, some users get it when the app has been idle for a while, other users get it when they are active.

In Sentry I can see a `404` returned from your API, url: 

`https://api.appcues.net/v1/accounts/{accountId}/users/{userId}/experience_content/{experienceId}`

Using Expo, SDK51, version 3.1.14 of `@appcues/react-native`.

**Comment by iujames** [comment]
Hi @jp1987 - thanks for the details here, it is very helpful for our api team to try and diagnose what may be occurring here. We are looking into this and will let you know what we find shortly. It does not seem like anything is incorrect about your usage.

Not required, but just to suggest alternative approaches - you can also trigger custom events and then set up flows to show when those events occur, if your account is set up for event triggering. This gives an additional layer of flexibility as you do not need to hardcode an experience ID anywhere in your product, and can change which experience is used over time as needed. This concept would give effectively the same result as the `show(id)` approach, but use `track(event)` instead with a flow configured to show on that event in Appcues studio.

**Comment by jp1987** [comment]
Thanks, we'll change our implementation to `Appcues.track`, seems handy!

**Comment by jp1987** [comment]
`Appcues.track` seems to have fixed this issue for us, haven't seen it since.
