### ISSUE TITLE
Certain functions are undefined on iOS

### ISSUE THREAD

**Issue by Lump01** [appcues/appcues-react-native-module#167]
After following the setup docs I still cannot use several functions.

`Appcues.track()` doesn't work as it will crash the app because it's undefined. `Appcues.setup()` and `Appcues.identify()` seem to work as they don't crash the app.

React Native - 0.74.6
Appcues - 4.0.1

### Setup in App.js
```
useEffect(() => {
    async function setupAppcues() {
      await Appcues.setup('appID', 'code');
      await Appcues.identify('Jonathan');
      Appcues.track('asdfasdfasdf');
    }
    setupAppcues().then();
  }, []);
```

### Usage in the app
```
<Button
  type={'mini'}
  color={'primary'}
  icon={'add'}
  onPress={() => {
    Appcues.track('Add button');
    setAddOpen(!addOpen);
  }}
  margin={'none'}
/>
```

**Comment by iujames** [comment]
Hi @Lump01, this is unexpected, and we can certainly try to help you pinpoint what may be going on here. 

First, would  like to confirm the install instructions [here](https://github.com/appcues/appcues-react-native-module/tree/main?tab=readme-ov-file#standard-installation), including the iOS `pod install` step.

1. In your app's root directory, install the Appcues React Native Module
   ```sh
   npm install --save @appcues/react-native
   # OR
   yarn add @appcues/react-native
   ```
2. Under your application's `ios` folder, run
   ```sh
   pod install
   ```

Is there any error message given in this case, or can you provide any more details about the app crash you're seeing? Double checking, this is not an Expo app, correct? I'm wondering if perhaps the `setupAppcues()` function isn't getting called before the usage in the `<Button ... />` example. Even so, that should not crash the application.

We have a reference application in the `example` folder in this repo, if that helps at all to compare implementation code. In that app, the Appcues SDK is initialized [here](https://github.com/appcues/appcues-react-native-module/blob/main/example/App.js#L25), and an example usage of tracking events can be found on the Events tab [here](https://github.com/appcues/appcues-react-native-module/blob/main/example/screens/main/EventsScreen.js#L22).

For the actual `track` implementation itself, that function is defined in the iOS native module [here](https://github.com/appcues/appcues-react-native-module/blob/main/ios/AppcuesReactNative.m#L18), and implemented [here](https://github.com/appcues/appcues-react-native-module/blob/main/ios/AppcuesReactNative.swift#L94-L96).

The versions of React Native and the Appcues module you are using look good, thank you for providing that.

**Comment by Lump01** [comment]
@iujames Thanks for getting back to me. 

It's weird because in the code sample labeled "Setup in App.js" the `Appcues.identify()` method works because I see the user ID of "Jonathan" in Audiences > Users.

The code sample labeled "Usage in the app" is a later page that is under that same navigation tree as the "Setup in App.js". I have even tried calling `Appcues.setup()` again in the exact same page as the "Usage in the app" code sample to no avail.

My project is not expo, it's base React Native.

Here's the error I get on press of that button:
![image](https://github.com/user-attachments/assets/3e1344aa-0fda-4c5e-9388-41835aaa49f7)

**Comment by Lump01** [comment]
My apologies for the bother... I wrote this code at the end of the day.

I just realized that I wrote this:
`import Appcues from '@appcues/react-native';`

instead of this as my import statement:
`import * as Appcues from '@appcues/react-native';`

It now works!

**Comment by iujames** [comment]
Excellent! was just about to ask about that `import` 😀 - thanks for trying it out! Let us know if you have any further questions we can help with.
