### ISSUE TITLE
Difference between 1.0.2 and 1.1.0

### ISSUE THREAD

**Issue by janirho** [appcues/appcues-react-native-module#55]
Hi team!
Are there any meaningful differences between these two versions? I am asking because using 1.0.2 would allow us to postpone compileSdk bump to the newest version as it is causing build issues for us.

Thanks!

**Comment by iujames** [comment]
Hi @janirho - thanks for reaching out!

I'd definitely recommend upgrading to 1.1.0 as soon as possible, but can also confirm that using 1.0.2 for the short term will not cause any issues with building and rendering Appcues content, using the current content block options. 

1.1.0 brings several nice updates - the most significant being support for the upcoming survey components coming soon in the Appcues builder. These will allow you to capture user input in text and selection options, much like the survey components available with Appcues web. Any flow built that uses these new components will require the client to upgrade to the 1.1.0 SDK, to be rendered. Other updates include: improvements in flow analytics reporting, improvements in side-by-side layout handling, and support for control experiments. 

The specific reason the Android compileSdk bump is required is our internal upgrade to Jetpack Compose 1.3.0, which included fixes in underlying components related to how text wraps and scales on different viewports (and many other internal upgrades provided in that library). This version of Compose requires compileSdk 33. We're certainly aware that upgrades can take time and effort, though. We intend to be mindful of this and careful about balancing the need for improvements and fixes with the upgrade timelines of customers.

Full details on the changes in the native libraries that are used by this React Native module can be found in the [iOS](https://github.com/appcues/appcues-ios-sdk/releases/tag/1.1.0) and [Android](https://github.com/appcues/appcues-android-sdk/releases/tag/1.1.0) releases.

**Comment by janirho** [comment]
Cool thanks for such a quick turnaround! Actually managed to get it sorted so now looking forward to those survey component on mobile 🚀
