### ISSUE TITLE
Error: CFBundleURLSchemes value missing React Native 

### ISSUE THREAD

**Issue by shahbaaz207** [appcues/appcues-react-native-module#70]
I have got an error in Appcuse debugger when try to Appcuse Deep Link 
```
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLName</key>
        <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>appcues-APPCUES_APPLICATION_ID</string>
        </array>
    </dict>
</array>
```
I have to add this schema to the info.plist file

**Comment by mmaatttt** [comment]
Hi Shahbaaz,

Have you seen our guide for [Configuring the Appcues URL Scheme](https://github.com/appcues/appcues-react-native-module/blob/main/docs/URLSchemeConfiguring.md)? Is there a specific step where you're having an issue?

Note that you need to replace `APPCUES_APPLICATION_ID` in the snippet with your app's specific Appcues Application ID that can be found in your [Appcues Studio settings](https://studio.appcues.com/settings/installation).

**Comment by shahbaaz207** [comment]
It's give Appcues SDK not receive link

**Comment by shahbaaz207** [comment]
Also, I have to get an Error in Android AndroidManifest intent-filter schema missing 
but add this line to the app folder AndroidManifest.xml
          <intent-filter>
				<action android:name="appcues-application-id" />
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
    		</intent-filter>
please look into it

**Comment by mmaatttt** [comment]
There's two issues with that snippet. You have `<action android:name="appcues` when it should be `<data android:scheme ="appcues` and you need to replace `application-id` in your snippet with your actual Appcues Application ID. So for example, if your application ID were `b3509ffa`, the snippet should be
```
<intent-filter>
	<data android:scheme ="appcues-b3509ffa" />
	<action android:name="android.intent.action.VIEW" />
	<category android:name="android.intent.category.DEFAULT" />
	<category android:name="android.intent.category.BROWSABLE" />
</intent-filter>
```

**Comment by shahbaaz207** [comment]
what is this mean by Error2: It gives Appcues SDK does not receive a link

**Comment by mmaatttt** [comment]
`Error 2` means that the URL scheme is properly registered, but the Appcues SDK did not receive the link from the host app. 

Most likely, you need to implement the `Linking` event listener shown in the [Handle the Custom URL Scheme](https://github.com/appcues/appcues-react-native-module/blob/main/docs/URLSchemeConfiguring.md#handle-the-custom-url-scheme) section of the URL Scheme configuring documentation.
